---

# rolling_deploy
- hosts: app
  sudo: yes
  serial: 1
  vars:
   haproxyapp: lampapp
   giturl: https://github.com/rahimre/SampleWebSite
   app_version: release-0.01

  roles:
   - rolling_deploy
